# -*- coding: utf-8 -*-
"""Comp_Vision_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNXYJ_QbrF5epqNiFFwAkOk6sMF9ZbzN
"""

import cv2

print(cv2.__version__)

!wget https://moderncomputervision.s3.eu-west-2.amazonaws.com/images.zip
!unzip -qq images.zip

image = cv2.imread('./images/castara.jpeg')

from matplotlib import pyplot as plt
#Show the image with matplotlib
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.show()

def imshow(title = "", image=None):
  plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
  plt.title(title)
  plt.show()

image = cv2.imread('./images/Trump.jpg')

imshow("Displaying an image", image)

cv2.imwrite('output.jpg', image)

cv2.imwrite('output.png', image)

# Remember, images are arrays..
# We need to use numpy to display images dimensions

import numpy as np

image.shape[0]

print('Height of Image: {} pixels'.format(int(image.shape[0])))
print('Width of Image: {} pixels'.format(int(image.shape[1])))
print('Depth of Image: {} colors components'.format(int(image.shape[2])))

